/**
 * @generated by scripts/generate-schema.ts - DO NOT EDIT
 * Source: src/domain/schema.yaml
 *
 * Shared DDL constant used by both TypeScript (Electron/better-sqlite3)
 * and Rust (Tauri/rusqlite).
 *
 * WAL mode is enabled at connection time, not in DDL.
 */

export const SQLITE_SCHEMA = `
CREATE TABLE IF NOT EXISTS kit_schemas (
  kit_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  version INTEGER NOT NULL DEFAULT 1,
  state_keys TEXT NOT NULL DEFAULT '[]',
  event_types TEXT NOT NULL DEFAULT '[]',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS kit_state (
  kit_key TEXT NOT NULL,
  instance_id TEXT NOT NULL DEFAULT 'default',
  state TEXT NOT NULL DEFAULT '{}',
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (kit_key, instance_id)
);

CREATE TABLE IF NOT EXISTS kit_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kit_key TEXT NOT NULL,
  instance_id TEXT NOT NULL DEFAULT 'default',
  type TEXT NOT NULL,
  ts INTEGER NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS kit_config (
  kit_key TEXT PRIMARY KEY,
  config TEXT NOT NULL DEFAULT '{}',
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_kit ON kit_events(kit_key, ts);
CREATE INDEX IF NOT EXISTS idx_events_type ON kit_events(kit_key, type, ts);
`.trim()
