/**
 * @generated by scripts/generate-schema.ts - DO NOT EDIT
 * Source: src/domain/schema.yaml
 *
 * Core domain model shared by all platforms (Electron, Tauri, Web).
 * These types define the data contract between kits, IPC, storage, and MCP.
 */

export interface KitSchema {
  kitKey: string
  displayName: string
  description: string
  version: number
  stateKeys: string[]
  eventTypes: string[]
  createdAt: number
  updatedAt: number
}

export interface KitState {
  kitKey: string
  instanceId: string
  state: Record<string, unknown>
  updatedAt: number
}

export interface KitEventEntry {
  id: number
  kitKey: string
  instanceId: string
  type: string
  ts: number
  payload: Record<string, unknown>
}

export interface KitConfig {
  kitKey: string
  config: Record<string, unknown>
  updatedAt: number
}

// ─── Event query options ───────────────────────────────────

/** Options for querying events */
export interface EventQueryOptions {
  /** Filter by event type */
  type?: string
  /** Only return events after this timestamp (epoch ms) */
  since?: number
  /** Maximum number of events to return (default: 100) */
  limit?: number
}
