use serde::{Deserialize, Serialize};

// @generated by scripts/generate-schema.ts - DO NOT EDIT
// Source: src/domain/schema.yaml

pub const SCHEMA_SQL: &str = "
CREATE TABLE IF NOT EXISTS kit_schemas (
  kit_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  version INTEGER NOT NULL DEFAULT 1,
  state_keys TEXT NOT NULL DEFAULT '[]',
  event_types TEXT NOT NULL DEFAULT '[]',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS kit_state (
  kit_key TEXT NOT NULL,
  instance_id TEXT NOT NULL DEFAULT 'default',
  state TEXT NOT NULL DEFAULT '{}',
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (kit_key, instance_id)
);

CREATE TABLE IF NOT EXISTS kit_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kit_key TEXT NOT NULL,
  instance_id TEXT NOT NULL DEFAULT 'default',
  type TEXT NOT NULL,
  ts INTEGER NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS kit_config (
  kit_key TEXT PRIMARY KEY,
  config TEXT NOT NULL DEFAULT '{}',
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_kit ON kit_events(kit_key, ts);
CREATE INDEX IF NOT EXISTS idx_events_type ON kit_events(kit_key, type, ts);
";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KitSchemaData {
    pub kit_key: String,
    pub display_name: String,
    pub description: String,
    pub version: i64,
    pub state_keys: Vec<String>,
    pub event_types: Vec<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KitStateData {
    pub kit_key: String,
    pub instance_id: String,
    pub state: serde_json::Value,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KitEventEntry {
    pub id: i64,
    pub kit_key: String,
    pub instance_id: String,
    #[serde(rename = "type")]
    pub event_type: String,
    pub ts: i64,
    pub payload: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KitConfigData {
    pub kit_key: String,
    pub config: serde_json::Value,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventQueryOptions {
    #[serde(rename = "type")]
    pub event_type: Option<String>,
    pub since: Option<i64>,
    pub limit: Option<i64>,
}
