packages:
  - "apps/*"
  - "kits/*"
  - "packages/*"
allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  electron: true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
minimumReleaseAgeExclude:
  - '@insightop/libopenblt@0.1.0'
onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - electron
  - esbuild
  - sharp
  - vue-demi
  - workerd
