name = "weblink"
compatibility_date = "2026-06-01"

[pages]
build_output_dir = "apps/web/dist"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomSignaling"
script_name = "webrtckit-room-worker"
